brie/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from tastypie.api import Api
from ricotta.api import UserResource, LocationResource, ShiftResource, PlannerBlockResource

v1_api = Api(api_name = 'v1')
v1_api.register(UserResource())
v1_api.register(LocationResource())
v1_api.register(ShiftResource())
v1_api.register(PlannerBlockResource())

admin.autodiscover()

urlpatterns = patterns('',
    url(r'^api/', include(v1_api.urls)),                    
    url(r'^ricotta/', include('ricotta.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include('cms.urls')),
)

ricotta/urls.py
from django.conf.urls import patterns, include, url
from django.views.generic import DetailView, ListView, TemplateView
from ricotta.views import EmployeesView
from django.contrib.auth.models import User

urlpatterns = patterns('',
    url(r'^$', 'ricotta.views.home'),
    url(r'^clockin/$', 'ricotta.views.clockin', name='clock-in'),

    url(r'^calendar/$', 'ricotta.views.calendar_base', name='calendar-home'),
    url(r'^calendar/trade_summary/$', 'ricotta.views.trade_summary', name='trade-summary'),
    url(r'^calendar/(?P<location_name>.*)/$', 'ricotta.views.calendar'),
    url(r'^shifts/(?P<username>\w+)/$', 'ricotta.views.shifts', name='my-shifts'),
    url(r'^planner/(?P<username>\w+)/$', 'ricotta.views.planner', name='edit-own-planner'),
    url(r'^planner/lab/(?P<location_name>\w+)/$', 'ricotta.views.planner_lab'),

    url(r'^timeclock/(?P<username>\w+)/$', 'ricotta.views.timeclock', name='view-timeclock'),
    url(r'^timeclock/(?P<username>\w+)/(?P<pastperiod>\d+)/$', 'ricotta.views.timeclock', name='view-timeclock'),
    url(r'^timeclocks_all/$', 'ricotta.views.timeclocks_all', name='timeclocks-all'),
    url(r'^whos_clockin/$', 'ricotta.views.whos_clockin', name='whos-clockin'),

    url(r'^employees/$', EmployeesView.as_view(), name='employees'),
    url(r'^employees/(?P<pk>\d+)/$',
        DetailView.as_view(
            model=User,
            template_name='ricotta/employee.html',
            context_object_name = 'user_object'),
        name='employee-detail'),
    url(r'^employees/(?P<location_name>.*)/$', EmployeesView.as_view(),
        name='employees-by-lab'),
)

ricotta/models.py
from django.db import models
from django.db.models.signals import post_save
from django.contrib.auth.models import User
from datetime import datetime
from django.utils import timezone
from tastypie.models import create_api_key
from string import *

class Listserv(models.Model):
    email = models.CharField(max_length=50, primary_key=True)
    
    def __unicode__(self):
        return self.email

class Location(models.Model):
    location_name = models.CharField(max_length=20, primary_key=True)
    address = models.CharField(max_length=50)
    phone_number = models.CharField(max_length=50)
    ip_address = models.IPAddressField()
    enable_schedule = models.BooleanField()
    
    def __unicode__(self):
        return self.location_name

class UserProfile(models.Model):
    user = models.OneToOneField(User)
    phone_number = models.CharField(max_length=12)
    lab = models.ForeignKey(Location, blank=True)
    listservs = models.ManyToManyField(Listserv, blank=True)
    
    def __unicode__(self):
        return self.user.username

User.profile = property(lambda u: UserProfile.objects.get(user=u))

class DisciplineRecord(models.Model):
    STATUS_CHOICES = (
        ('nd', 'No Discipline'),
        ('vw', 'Verbal Warning'),
        ('wu', 'Write-Up'),
        ('pr', 'Probation'),
    )
    date_of_record = models.DateTimeField()
    employee = models.ForeignKey(User, related_name='disciplined_employee')
    changed_by = models.ForeignKey(User)
    status_name = models.CharField(max_length=3, choices = STATUS_CHOICES)
    comment = models.TextField()

    def __unicode__(self):
        return ' '.join((self.employee.username,
                         self.date_of_record.strftime("%y-%m-%d")))

    class Meta:
        permissions = (
            ("view_dr", "View discipline record"),
        )

class Shift(models.Model):
    start_time = models.DateTimeField()
    end_time = models.DateTimeField()
    location_name = models.ForeignKey(Location)
    worker = models.ForeignKey(User, null=True)
    for_trade = models.BooleanField()
    been_traded = models.BooleanField()

    def __unicode__(self):
        return ' '.join((self.location_name.location_name,
                         self.start_time.astimezone(timezone.get_default_timezone()).strftime("%Y-%m-%d %H:%M:%S"),
                         self.worker.username))
            
class PlannerBlock(models.Model):
    PLANNER_CHOICES = (
        ('pf', 'Preferred'),
        ('ic', 'In Class'),
        ('un', 'Unavailable'),
    )

    start_time = models.DateTimeField()
    end_time = models.DateTimeField()
    worker = models.ForeignKey(User, null=True)
    block_type = models.CharField(max_length=2, choices = PLANNER_CHOICES)

    def __unicode__(self):
        return ' '.join((self.worker.username,
                         self.start_time.astimezone(timezone.get_default_timezone()).strftime("%Y-%m-%d %H:%M:%S"),
                         self.get_block_type_display()))


class TimeclockRecord(models.Model):
    start_time = models.DateTimeField()
    end_time = models.DateTimeField()
    inIP = models.IPAddressField()
    outIP = models.IPAddressField()
    employee = models.ForeignKey(User)
    
    def __unicode__(self):
        return ' '.join((self.employee.username, 
                         self.start_time.astimezone(timezone.get_default_timezone()).strftime("%Y-%m-%d %H:%M:%S"), 
                         self.inIP))

class TimeclockAction(models.Model):
    time = models.DateTimeField()
    IP = models.IPAddressField()
    employee = models.ForeignKey(User)

    def __unicode__(self):
        return ' '.join((self.employee.username,
                         self.time.astimezone(timezone.get_default_timezone()).strftime("%Y-%m-%d %H:%M:%S"), 
                         self.IP))

# this is to generate the tastypie API keys for each user
models.signals.post_save.connect(create_api_key, sender=User)

ricotta/views.py
from django.template import RequestContext, Context, loader
from ricotta.models import Shift, Location, UserProfile, PlannerBlock, TimeclockRecord, TimeclockAction
from django.contrib.auth.models import User
from django.views.generic import DetailView, ListView
from django.http import HttpResponse, Http404, HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from django.db.models import Count
from datetime import timedelta
from django.utils import timezone
import pdb
import array

def home(request):
    return render(request, 'ricotta/home.html',
                  {"worker": request.user.username,
                   "lab": request.user.profile.lab})

def clockin(request):
    ta = TimeclockAction.objects.filter(employee=request.user)

    try:
        real_ip = request.META['HTTP_X_FORWARDED_FOR']
    except KeyError:
        real_ip = request.META['REMOTE_ADDR']

    if (ta):
        TimeclockRecord(start_time=ta[0].time,
                        end_time=timezone.now(),
                        employee=request.user,
                        inIP=ta[0].IP,
                        outIP=real_ip).save()
        ta.delete()
    else:
        TimeclockAction(time=timezone.now(),
                        employee=request.user,
                        IP=real_ip).save()
    return HttpResponseRedirect('/')

def whos_clockin(request):
    clocked_in = TimeclockAction.objects.all()

    return render(request, 'ricotta/whos_clockin.html',
                  {"clocked_in": clocked_in,
                   "title": "Who's Clocked In"})

def calendar_base(request):
    calendars = Location.objects.all()
    return render(request, 'ricotta/calendar_none.html',
                  {"calendars": calendars})

def calendar(request, location_name):
    get_object_or_404(Location, pk=location_name)

    return render(request, 'ricotta/calendar.html',
                  {"location_name": location_name,
                   "worker": request.user})

def trade_summary(request):
    return render(request, 'ricotta/trade_summary.html',
                  {"worker": request.user})

def planner(request, username):
    get_object_or_404(User, username=username)

    return render(request, 'ricotta/planner.html',
                  {"worker": request.user,
                   "preferences": PlannerBlock.PLANNER_CHOICES})

def planner_lab(request, location_name):
    get_object_or_404(Location, pk=location_name)
    workers = UserProfile.objects.filter(lab=location_name)

    return render(request, 'ricotta/planner_lab.html',
                  {"workers": workers,
                   "location_name": location_name})

def calc_timeperiod(pastperiod):
    # the 5 hours correction is for UTC time
    next_sat = timezone.now().replace(hour=0, minute=0, second=0, microsecond = 0) + timedelta(5 - timezone.now().weekday())
    return {"start": next_sat - timedelta(weeks=pastperiod * 2) - timedelta(weeks=2, days=1, hours=5),
            "end": next_sat - timedelta(weeks=pastperiod * 2)}

def sum_timeclocks(data):
    return reduce(lambda h, e: h + (e.end_time - e.start_time),
                  data, timedelta(0))

def kronos_round(t):
    return round(t.total_seconds() / 3600, 2)

def timeclock(request, username, pastperiod=0):
    user = User.objects.get(username=username)
    period = calc_timeperiod(int(pastperiod))
    tr_data = user.timeclockrecord_set.filter(start_time__range=(period['start'], period['end']))
    sh_data = user.shift_set.filter(start_time__range=(period['start'], period['end']))

    total_clocked = sum_timeclocks(tr_data)
    total_scheduled = sum_timeclocks(sh_data)

    return render(request, 'ricotta/timeclock.html',
                  {"worker": user.username,
                   "tr_data": tr_data,
                   "total_scheduled": kronos_round(total_scheduled),
                   "total_clocked": kronos_round(total_clocked),
                   "title": "Timeclock for " + user.username,
                   "pastperiod": pastperiod})

def timeclocks_all(request, pastperiod=0):
    period = calc_timeperiod(int(pastperiod))

    users = User.objects.all()
    clockin_data = []
    for u in users:
        total_clocked = sum_timeclocks(u.timeclockrecord_set.filter(start_time__range=(period['start'], period['end'])))
        total_scheduled = sum_timeclocks(u.shift_set.filter(start_time__range=(period['start'], period['end'])))

        clockin_data.append({"user": u,
                             "total_clocked": kronos_round(total_clocked),
                             "total_scheduled": kronos_round(total_scheduled)})

    return render(request, 'ricotta/timeclocks_all.html',
                  {"timeclock_data": clockin_data})


def shifts(request, username):
    shift_data = Shift.objects.filter(worker=request.user).filter(start_time__range=(timezone.now(), timezone.now() + timedelta(weeks=1)))

    return render(request, 'ricotta/shift.html',
                  {"worker": request.user.username,
                   "shift_data": shift_data})

class EmployeesView(ListView):
    template_name = 'ricotta/employees.html'
    context_object_name='user_queryset'

    def separate_groups(self, q):
        return {"conleaders": q.filter(is_staff=True),
                "consultants": q.exclude(is_staff=True)}

    def get_queryset(self):
        try:
            self.kwargs['location_name']
        except:
            return self.separate_groups(User.objects.all())
        else:
            return self.separate_groups(User.objects.filter(userprofile__lab=self.kwargs['location_name']))

    def get_context_data(self, **kwargs):
        context = super(EmployeesView, self).get_context_data(**kwargs)
        try:
            self.kwargs['location_name']
        except:
            context['title'] = "All Employees"
        else:
            context['title'] = "Employees in " + self.kwargs['location_name']
        return context

brie/templates/ricotta/calendar.html
{% extends "ricotta/calendar_base.html" %}
{% load sekizai_tags cms_tags %}

{% block title %}{{ location_name }} Calendar{% endblock %}

{% block custom_api_info %}
{% addtoblock "js" %}
<script>
  SHIFTS_API = "{% url api_dispatch_list api_name="v1" resource_name="shift" %}?location_name__location_name={{ location_name }}";
  USERS_API = "{% url api_dispatch_list api_name="v1" resource_name="user" %}";
  
  Backbone.Tastypie.apiKey = {
      username: '{{ worker.username }}',
      key: '{{ worker.api_key.key }}'
  };
  
</script>
{% endaddtoblock %}
{% endblock %}

{% block calendar_app %}
{% addtoblock "js" %}
<script src="{{ STATIC_URL }}js/application.js"></script>
{% endaddtoblock %}
{% endblock %}
  
{% block dialog %}
<div id='eventDialog' class='dialog ui-helper-hidden'>
  <form>
    <div> 
      <label>Consultant:</label>
      <select id='conWorking' class="field"></select>
      <input id='loc' type='hidden' value='{{ location_name }}'></input>
    </div>
  </form>
</div>
{% endblock %}

brie/templates/ricotta/calendar_base.html
{% extends "base.html" %}
{% load sekizai_tags cms_tags %}

{% block title %}{% endblock %}
{% block base_content %}
{% block calendar_scripts %}
{% addtoblock "css" %}<link rel='stylesheet' type='text/css' href="{{ STATIC_URL }}css/fullcalendar.css"/>{% endaddtoblock %}
{% addtoblock "css" %}<link rel='stylesheet' type='text/css' href="{{ STATIC_URL }}css/jquery-ui-1.8.21.custom.css"/>{% endaddtoblock %}
{% addtoblock "css" %}<link rel='stylesheet' type='text/css' href="{{ STATIC_URL }}css/application.css"/>{% endaddtoblock %}

{% addtoblock "js" %}<script src="{{ STATIC_URL }}js/jquery-1.7.2.min.js"></script>{% endaddtoblock %}
{% addtoblock "js" %}<script src="{{ STATIC_URL }}js/jquery-ui-1.8.21.custom.min.js"></script>{% endaddtoblock %}
{% addtoblock "js" %}<script src="{{ STATIC_URL }}js/underscore-min.js"></script>{% endaddtoblock %}
{% addtoblock "js" %}<script src="{{ STATIC_URL }}js/backbone-min.js"></script>{% endaddtoblock %}
{% addtoblock "js" %}<script src="{{ STATIC_URL }}js/fullcalendar.min.js"></script>{% endaddtoblock %}
{% addtoblock "js" %}<script src="{{ STATIC_URL }}js/backbone-tastypie.js"></script>{% endaddtoblock %}
{% endblock %}

{% block custom_api_info %}
{% endblock %}

{% block calendar_app %}
{% endblock %}

{% block description %}
{% endblock %}
<div id='calendar'></div>
    
  
{% block dialog %}
{% endblock %}
{% endblock %}

brie/templates/ricotta/calendar_none.html
{% extends "template_1.html" %}
{% load cms_tags %}

{% block base_content %}
  <ul>
  {% for calendar in calendars %}
    <li><a href='{{ calendar }}'>{{ calendar }}</a></li>
  {% endfor %}
  </ul>
{% endblock %}

brie/templates/ricotta/employee.html
{% extends "base.html" %}
{% load sekizai_tags cms_tags %}

{% block base_content %}
  <h2>{{user_object.first_name}} {{user_object.last_name}}</h2>
<p>NetID: {{user_object.username}} <br />
Email: {{user_object.email}} <br />
Phone: {{user_object.get_profile.phone_number}} <br />
Staff: {{user_object.is_staff}}
</p>

{% endblock %}

brie/templates/ricotta/employees.html
{% extends "base.html" %}
{% load sekizai_tags cms_tags ricotta_extras %}

{% block title %}{{ title }}{% endblock %}
{% block base_content %}
  <h2>{{ title }}</h2>
  <h3>Conleaders</h3>
  <table>
    <tr><th>NetID</th><th>First Name</th><th>Last Name</th><th>Email</th><th>Lab</th></tr>
    {% for e in user_queryset.conleaders %}
      {% url employee-detail e.pk as the_url %}
      <tr><td><a href="{{ the_url }}">{{e.username}}</a></td>
          <td>{{e.first_name}}</td>
          <td>{{e.last_name}}</td>
          <td>{{e.email}}</td>
          <td>{{e.profile.lab}}</td></tr>
    {% endfor %}
  </table>
  <h3>Consultants</h3>
  <table>
    <tr><th>NetID</th><th>First Name</th><th>Last Name</th><th>Email</th><th>Lab</th></tr>
    {% for e in user_queryset.consultants %}
      {% url employee-detail e.pk as the_url %}
      <tr><td><a href="{{ the_url }}">{{e.username}}</a></td>
          <td>{{e.first_name}}</td>
          <td>{{e.last_name}}</td>
          <td>{{e.email}}</td>
          <td>{{e.profile.lab}}</td></tr>
    {% endfor %}
  </table>

{% endblock %}

brie/templates/ricotta/home.html
{% extends "template_1.html" %}
{% load cms_tags %}

{% block title %}Conspace - Ricotta{% endblock %}
{% block base_content %}
<style type="text/css">
.box-header {
    text-align: center
}
#calendar-box {
    background-color: #fdfcb3;
    position: relative;
    padding: 15px;
    margin-top: 10px;
    margin-bottom: 30px;
    width: 25%;
    float: left
}

#timeclock-box {
    background-color: #fdfcb3;
    position: relative;
    padding: 15px;
    margin-top: 10px;
    width: 25%;
    margin-left: 15px;
    float: left
}

#employees-box {
    background-color: #fdfcb3;
    position: relative;
    padding: 15px;
    margin-top: 10px;
    width: 25%;
    margin-left: 15px;
    float: left
}
</style>
  <h2>Ricotta</h2>
  <p>Here are the pages for scheduling, timeclock, and employee management.</p>
  {% url clock-in as the_url %}
  <p><a href="{{ the_url }}">Clock In</a></p>
  <div id="calendar-box">
    <h4 class="box-header"><b>Calendar</b></h4>
    <ul>
      {% url calendar-home as the_url %}
      <li><a href="{{ the_url }}">Lab Schedules</a></li>
      {% url trade-summary as the_url %}
      <li><a href="{{ the_url }}">Shift Trade Summary</a></li>
      {% url my-shifts worker as the_url %}
      <li><a href="{{ the_url }}">My Shifts</a></li>
      {% url edit-own-planner worker as the_url %}
      <li><a href="{{ the_url }}">Edit My Planner</a></li>
    </ul>
  </div>
  <div id="timeclock-box">
    <h4 class="box-header"><b>Timeclock</b></h4>
    <ul>
      {% url view-timeclock worker as the_url %}
      <li><a href="{{ the_url }}">View My Timeclock</a></li>
      {% url whos-clockin as the_url %}
      <li><a href="{{ the_url }}">Who's on Shift</a></li>
      {% url timeclocks-all as the_url %}
      <li><a href="{{ the_url }}">Timeclock Cumulative View</a></li>
    </ul>
  </div>
  <div id="employees-box">
    <h4 class="box-header"><b>Employees</b></h4>
    <ul>
      {% url employees-by-lab lab as the_url %}
      <li><a href="{{ the_url }}">Employees in my Lab</a></li>
      {% url employees as the_url %}
      <li><a href="{{ the_url }}">Full Employee List</a></li>
    </ul>
  </div>
{% endblock %}

brie/templates/ricotta/index.html
{% if location_list %}
  <ul>
    {% for location in location_list %}
      <li>{{ location.location_name }}</li>
    {% endfor %}
  </ul>
{% else %}
  <p>No locations are available</p>
{% endif %}

brie/templates/ricotta/planner.html
{% extends "ricotta/calendar_base.html" %}
{% load sekizai_tags cms_tags %}

{% block title %}{{ worker }}'s Planner{% endblock %}

{% block custom_api_info %}
{% addtoblock "js" %}
<script>
  PLANNER_API = "{% url api_dispatch_list api_name="v1" resource_name="planner_block" %}?worker__username={{ worker }}";
  
  Backbone.Tastypie.apiKey = {
      username: '{{ worker.username }}',
      key: '{{ worker.api_key.key }}'
  };
</script>
{% endaddtoblock %}
{% endblock %}

{% block calendar_app %}
{% addtoblock "js" %}
<script src="{{ STATIC_URL }}js/planner_cal_app.js"></script>
{% endaddtoblock %}
{% endblock %}

{% block dialog %}
<div id='prefDialog' class='dialog ui-helper-hidden'>
  <form>
    <div> 
      <label>Preference:</label>
      <select id='prefBox' class="field">
        {% for p, pref in preferences %}
        <option value={{p}}>{{pref}}</option>
        {% endfor %}
      </select>
      <input id='user' type='hidden' value='/api/v1/user/{{ worker }}/'></input>
    </div>
  </form>
</div>
{% endblock %}

brie/templates/ricotta/planner_lab.html
{% extends "ricotta/calendar_base.html" %}

{% block title %}Compiled Planners for {{ location_name }} {% endblock %}
  
{% block resource_apis %}
  PLANNER_API = "{% url api_dispatch_list api_name="v1" resource_name="planner_block" %}?worker__username__in={{ workers|join:"," }}";
{% endblock %}
{% block calendar_js %}
  <script src="{{ STATIC_URL }}js/planner_cal_app.js"></script>
{% endblock %}

{% block dialog %}
{% endblock %}

brie/templates/ricotta/shift.html
{% extends "base.html" %}
{% load sekizai_tags cms_tags ricotta_extras %}

{% block base_content %}
  <table>
    <tr><th>Location</th><th>Start Time</th><th>End Time</th><th>Duration</th></tr>
    {% for shift in shift_data %}
      <tr><td>{{shift.location_name.location_name}}</td><td>{{shift.start_time}}</td><td>{{shift.end_time}}</td><td>{{shift.start_time|datetime_diff:shift.end_time}}</td></tr>
    {% endfor %}
  </table>
{% endblock %}

brie/templates/ricotta/timeclock.html
{% extends "base.html" %}
{% load sekizai_tags cms_tags ricotta_extras %}

{% block title %}{{ title }}{% endblock %}
{% block base_content %}
  <h2>My Timeclock</h2>
  <table>
    <tr><th>Start Time</th><th>End Time</th><th>In IP</th><th>Out IP</th>
        <th>Kronos Time</th></tr>
    {% for tr in tr_data %}
      <tr><td>{{tr.start_time}}</td><td>{{tr.end_time}}</td>
          <td>{{tr.inIP}}</td><td>{{tr.outIP}}</td><td>{{tr.start_time|datetime_diff:tr.end_time}}</td></tr>
    {% endfor %}
  </table>
  <p>Total scheduled time: {{ total_scheduled }}<br />
  Total clocked time: {{ total_clocked }}</p>
  <p>
  {% url view-timeclock worker pastperiod|add:"1" as the_url %}
  <a href="{{ the_url }}">Back</a>
  {% url view-timeclock worker pastperiod|add:"-1" as the_url %}
  <a href="{{ the_url }}">Forward</a>
  </p>
{% endblock %}

brie/templates/ricotta/timeclocks_all.html
{% extends "base.html" %}
{% load sekizai_tags cms_tags ricotta_extras %}

{% block title %}Timeclock Cumulative View{% endblock %}
{% block base_content %}
  <h2>Timeclock Cumulative View</h2>
  <table>
    <tr><th>Employee</th><th>Total Clocked</th><th>Total Scheduled</th></tr>
    {% for td in timeclock_data %}
      {% url view-timeclock td.user.username as the_url %}
      <tr><td><a href={{ the_url }}>{{td.user.username}}</a></td><td>{{td.total_clocked}}</td>
          <td>{{td.total_scheduled}}</td>
    {% endfor %}
  </table>

{% endblock %}

brie/templates/ricotta/trade_summary.html
{% extends "ricotta/calendar_base.html" %}
{% load sekizai_tags cms_tags %}

{% block title %}{{ location_name }} Calendar{% endblock %}

{% block custom_api_info %}
{% addtoblock "js" %}
<script>
  SHIFTS_API = "{% url api_dispatch_list api_name="v1" resource_name="shift" %}?for_trade=True";
  USERS_API = "{% url api_dispatch_list api_name="v1" resource_name="user" %}";
  
  Backbone.Tastypie.apiKey = {
      username: '{{ worker.username }}',
      key: '{{ worker.api_key.key }}'
  };
    
</script>
{% endaddtoblock %}
{% endblock %}

{% block calendar_app %}
{% addtoblock "js" %}
<script src="{{ STATIC_URL }}js/trade_summary_app.js"></script>
{% endaddtoblock %}
{% endblock %}

{% block description %}
<h2>Trade Shift Summary</h2>
<p>These are all the shifts which are currently up for trade in all of the labs, represented in one calendar. You may click on any shift to take it.</p>
<p><b>PC-MAC</b>: green, <b>IC-Main</b>: red, <b>IC-Media</b>: orange, <b>SCV Tech</b>: blue, <b>SCV Library</b>: purple, <b>Tech</b>: yellow</p>

{% endblock %}
  
{% block dialog %}
<div id='eventDialog' class='dialog ui-helper-hidden'>
  <form>
    <div> 
      <label>Consultant:</label>
      <select id='conWorking' class="field"></select>
    </div>
  </form>
</div>
{% endblock %}

brie/templates/ricotta/whos_clockin.html
{% extends "base.html" %}
{% load sekizai_tags cms_tags ricotta_extras %}

{% block title %}{{ title }}{% endblock %}
{% block base_content %}
  <h2>{{ title }}</h2>
  <table>
    <tr><th>Name</th><th>Since (Time)</th><th>Location</th><th>Next Person</th></tr>
    {% for ta in clocked_in %}
      <tr><td>{{ta.employee.first_name}} {{ta.employee.last_name}}</td><td>{{ta.time}}</td>
          <td>{{ta.IP|ip_to_lab}}</td><td>{{ta|next_shift}}</td></tr>
    {% endfor %}
  </table>
{% endblock %}